//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ddbind
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetails_Tab
    {
        public int Sid { get; set; }
        public int StateId { get; set; }
        public int Did { get; set; }
        public string name { get; set; }
        public int Sage { get; set; }
        public string SPhoto { get; set; }
    }
}
